### ISSUE TITLE
Issues should be linked if they are mentioned in the commit

### ISSUE THREAD

**Issue by wardtm11** [nazrhyn/gitlab-slack#1]
If an issue is mentioned in the commit anywhere after the first line, it won't be sent to Slack.  A possible feature could be to detect issue mentions in the entire commit message, and then display them with their own label alongside of the commit for easy access.

**Comment by nazrhyn** [comment]
Good idea. I'm currently truncating commit messages to the summary line, but I'll do the issue mentions scan on the full commit message and just pull together a list to print somewhere in the notification.
