### ISSUE TITLE
Unrecognized Data

### ISSUE THREAD

**Issue by bingofly** [nazrhyn/gitlab-slack#21]
```
{
    "before": "ba7120f8f2fa7fc05be129a63a8d44524a9b6755",
    "after": "488f91c0e80f7e1f21a232465249d130a8183440",
    "ref": "refs/heads/develop",
    "user_id": 18,
    "user_name": "fuyi.liu",
    "project_id": 185,
    "repository": {
        "name": "*******",
        "url": "*******",
        "description": "*******",
        "homepage": "*******"
    },
    "commits": [
        {
            "id": "488f91c0e80f7e1f21a232465249d130a8183440",
            "message": "*******",
            "timestamp": "2016-08-23T13:47:59+08:00",
            "url": "*******",
            "author": {
                "name": "*******",
                "email": "*******"
            }
        }
    ],
    "total_commits_count": 1
}
```

When I push to gitlab slack is Unrecognized Data

**Comment by nazrhyn** [comment]
That POST is missing the `object_kind` property. A long time ago, GitLab updated their webhooks to all include that property which is used to differentiate the types. What version of GitLab are you on?

**Comment by bingofly** [comment]
My GitLab version is 7.6.2.

**Comment by nazrhyn** [comment]
If it doesn't have the `object_kind` property, it's too old for this. Sorry about that.

**Comment by pdericson** [comment]
@bingofly I'm having the same issue with gitlab 6.  I made a few changes based on @nazrhyn's comment above.

https://github.com/pdericson/gitlab-slack/tree/gitlab-6

**Comment by nazrhyn** [comment]
@pdericson If you'd like to make a PR based on your changes, I'd be happy to review it!
