### ISSUE TITLE
Can not active Slack on LOCAL Gitlab

### ISSUE THREAD

**Issue by mainguyendn19960519** [nazrhyn/gitlab-slack#22]
I am integrating Slack and Local Gitlab.
When I checkbox active Slack on Local Gitlab. The error is: **Something went wrong on our end**
![1](https://user-images.githubusercontent.com/26568604/27620670-448eb7c2-5bf5-11e7-88d0-5f80ab1f59e3.PNG)

![2](https://user-images.githubusercontent.com/26568604/27620672-45e4eace-5bf5-11e7-9a8e-8aef27c5f52d.PNG)

**Comment by nazrhyn** [comment]
It doesn't look like you're using this code. If you need help with using the built-in Slack integration provided by GitLab, you'll need to check out their help resources.

**Comment by dibustosb** [comment]
@mainguyendn19960519 You could solve this??? i have the same error on my local gitlab

**Comment by nazrhyn** [comment]
@dibustosb If both of you are having issues with the built-in Slack integration, this is not the place to discuss it :smile:.
