### ISSUE TITLE
Add label change tracking

### ISSUE THREAD

**Issue by nazrhyn** [nazrhyn/gitlab-slack#7]
Add label change tracking by keeping track of existing issue label state and monitoring the issues on update events.

* Add configuration per project for labels of interest.
* On start up...
  * Fetch each project's labels and cache.
  * Fetch each project's open issues and cache label information.
* For modified issues, branch to another function...
  * Compare the label states.
  * Update the cache.
  * Send a Slack message with an attachment per label with "**Added|Removed** \_label_name_".
* For new or closed issues, update the cache accordingly.

**Comment by nazrhyn** [comment]
I got the design for the async project/label fetches implemented for a single project. Need to expand to multiple projects then put it in place for startup. Then on to issue modification handling.

**Comment by nazrhyn** [comment]
Almost completed this today. Issues are tracked based on per-project "relevant labels" configuration. Here are some examples:

![image](https://cloud.githubusercontent.com/assets/1672405/10551018/44b57d9c-7418-11e5-95ac-a5df0d9b8448.png)

I need to update the CHANGELOG and add some more information to the README and the I'll be pushing these changes. This upcoming push will fix #8 and #9, as well.

**Comment by spodlecki** [comment]
+1 Looks great to me, though we don't really use gitlab issue tracking -- we host those through JIRA. We do use the Merge Requests though

**Comment by nazrhyn** [comment]
Yeah, I admit to having completely ignored that for similar reasons: we
don't use the merge requests.

**Comment by nazrhyn** [comment]
@spodlecki No idea if you still use this, but just did a big rewrite and now support MRs and wiki page events.
